#!/bin/bash
# 1. Initialize the variable
i=1

# 2. Set the condition (While i is less than or equal to 10)
while [ $i -le 10 ]
do
    echo "Best School"
    
    # 3. Increment the variable (Add 1 to i)
    ((i++))
done
